server:
  port: 8080

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      uri: http://config-server:8888
    bootstrap:
      enabled: true

  config:
    import: configserver:http://config-server:8888

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
