server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: fechadinho-gateway
  config:
    import: configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: rota
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/rota/**
          filters:
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: campeao
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/campeao/**
          filters:
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: conhecido
          uri: lb://JOGADOR-SERVICE
          predicates:
            - Path=/conhecido/**
          filters:
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: convidado
          uri: lb://JOGADOR-SERVICE
          predicates:
            - Path=/convidado/**
          filters:
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: jogador
          uri: lb://JOGADOR-SERVICE
          predicates:
            - Path=/jogador/**
          filters:
            - name: UserAuthentication
              args:
                headerName: Authorization
        - id: partida
          uri: lb://PARTIDA-SERVICE
          predicates:
            - Path=/partida/**
          filters:
            - StripPrefix=1
            - name: UserAuthentication
              args:
                headerName: Authorization
logging:
  level:
    org.springframework.cloud.gateway: TRACE
