server:
  port: 8099

spring:
  application:
    name: partida-service
  main:
    allow-bean-definition-overriding: true

  config:
    import: configserver:http://localhost:8888

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      resourceService:
        register-health-indicator: true
        minimum-number-of-calls: 1
        sliding-window-size: 3
        wait-duration-in-open-state:
          seconds: 200

      jogadorService:
        register-health-indicator: true
        minimum-number-of-calls: 1
        sliding-window-size: 3
        wait-duration-in-open-state:
          seconds: 200
