server:
  port: 8099

spring:
  application:
    name: partida-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:partida
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      resourceService:
        register-health-indicator: true
        minimum-number-of-calls: 1
        sliding-window-size: 3
        wait-duration-in-open-state:
          seconds: 200

      jogadorService:
        register-health-indicator: true
        minimum-number-of-calls: 1
        sliding-window-size: 3
        wait-duration-in-open-state:
          seconds: 200
