server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WagnerWD40/fechadinho-configs
          clone-on-start: true
          search-paths:
            - "config"
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG

