server:
  port: 8082

spring:
  application:
    name: resource-service
  config:
    import: configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
