server:
  port: 8080

spring:
  application:
    name: resource-service
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
