insert into rota (nome) values ('Top');
insert into rota (nome) values ('Jungle');
insert into rota (nome) values ('Mid');
insert into rota (nome) values ('ADC');
insert into rota (nome) values ('Suporte');

insert into campeao (id, nome) values (1, 'Annie');
insert into campeao (id, nome) values (10, 'Kayle');
insert into campeao (id, nome) values (101, 'Xerath');
insert into campeao (id, nome) values (102, 'Shyvana');
insert into campeao (id, nome) values (103, 'Ahri');
insert into campeao (id, nome) values (104, 'Graves');
insert into campeao (id, nome) values (105, 'Fizz');
insert into campeao (id, nome) values (106, 'Volibear');
insert into campeao (id, nome) values (107, 'Rengar');
insert into campeao (id, nome) values (11, 'Master Yi');
insert into campeao (id, nome) values (99, 'Lux');
insert into campeao (id, nome) values (110, 'Varus');
insert into campeao (id, nome) values (111, 'Nautilus');
insert into campeao (id, nome) values (112, 'Viktor');
insert into campeao (id, nome) values (113, 'Sejuani');
insert into campeao (id, nome) values (114, 'Fiora');
insert into campeao (id, nome) values (115, 'Ziggs');
insert into campeao (id, nome) values (117, 'Lulu');
insert into campeao (id, nome) values (119, 'Draven');
insert into campeao (id, nome) values (12, 'Alistar');
insert into campeao (id, nome) values (120, 'Hecarim');
insert into campeao (id, nome) values (121, 'Kha''Zix');
insert into campeao (id, nome) values (122, 'Darius');
insert into campeao (id, nome) values (126, 'Jayce');
insert into campeao (id, nome) values (127, 'Lissandra');
insert into campeao (id, nome) values (13, 'Ryze');
insert into campeao (id, nome) values (131, 'Diana');
insert into campeao (id, nome) values (133, 'Quinn');
insert into campeao (id, nome) values (134, 'Syndra');
insert into campeao (id, nome) values (136, 'Aurelion Sol');
insert into campeao (id, nome) values (14, 'Sion');
insert into campeao (id, nome) values (141, 'Kayn');
insert into campeao (id, nome) values (142, 'Zoe');
insert into campeao (id, nome) values (143, 'Zyra');
insert into campeao (id, nome) values (145, 'Kai''Sa');
insert into campeao (id, nome) values (147, 'Seraphine');
insert into campeao (id, nome) values (15, 'Sivir');
insert into campeao (id, nome) values (150, 'Gnar');
insert into campeao (id, nome) values (154, 'Zac');
insert into campeao (id, nome) values (157, 'Yasuo');
insert into campeao (id, nome) values (16, 'Soraka');
insert into campeao (id, nome) values (161, 'Vel''Koz');
insert into campeao (id, nome) values (163, 'Taliyah');
insert into campeao (id, nome) values (164, 'Camille');
insert into campeao (id, nome) values (166, 'Akshan');
insert into campeao (id, nome) values (17, 'Teemo');
insert into campeao (id, nome) values (18, 'Tristana');
insert into campeao (id, nome) values (19, 'Warwick');
insert into campeao (id, nome) values (2, 'Olaf');
insert into campeao (id, nome) values (20, 'Nunu & Willump');
insert into campeao (id, nome) values (200, 'Bel''Veth');
insert into campeao (id, nome) values (201, 'Braum');
insert into campeao (id, nome) values (202, 'Jhin');
insert into campeao (id, nome) values (203, 'Kindred');
insert into campeao (id, nome) values (21, 'Miss Fortune');
insert into campeao (id, nome) values (22, 'Ashe');
insert into campeao (id, nome) values (221, 'Zeri');
insert into campeao (id, nome) values (222, 'Jinx');
insert into campeao (id, nome) values (223, 'Tahm Kench');
insert into campeao (id, nome) values (23, 'Tryndamere');
insert into campeao (id, nome) values (233, 'Briar');
insert into campeao (id, nome) values (234, 'Viego');
insert into campeao (id, nome) values (235, 'Senna');
insert into campeao (id, nome) values (236, 'Lucian');
insert into campeao (id, nome) values (238, 'Zed');
insert into campeao (id, nome) values (24, 'Jax');
insert into campeao (id, nome) values (240, 'Kled');
insert into campeao (id, nome) values (245, 'Ekko');
insert into campeao (id, nome) values (246, 'Qiyana');
insert into campeao (id, nome) values (25, 'Morgana');
insert into campeao (id, nome) values (254, 'Vi');
insert into campeao (id, nome) values (26, 'Zilean');
insert into campeao (id, nome) values (266, 'Aatrox');
insert into campeao (id, nome) values (267, 'Nami');
insert into campeao (id, nome) values (268, 'Azir');
insert into campeao (id, nome) values (27, 'Singed');
insert into campeao (id, nome) values (28, 'Evelynn');
insert into campeao (id, nome) values (29, 'Twitch');
insert into campeao (id, nome) values (3, 'Galio');
insert into campeao (id, nome) values (30, 'Karthus');
insert into campeao (id, nome) values (31, 'Cho''Gath');
insert into campeao (id, nome) values (32, 'Amumu');
insert into campeao (id, nome) values (33, 'Rammus');
insert into campeao (id, nome) values (34, 'Anivia');
insert into campeao (id, nome) values (35, 'Shaco');
insert into campeao (id, nome) values (350, 'Yuumi');
insert into campeao (id, nome) values (36, 'Dr. Mundo');
insert into campeao (id, nome) values (360, 'Samira');
insert into campeao (id, nome) values (37, 'Sona');
insert into campeao (id, nome) values (38, 'Kassadin');
insert into campeao (id, nome) values (39, 'Irelia');
insert into campeao (id, nome) values (4, 'Twisted Fate');
insert into campeao (id, nome) values (40, 'Janna');
insert into campeao (id, nome) values (41, 'Gangplank');
insert into campeao (id, nome) values (412, 'Thresh');
insert into campeao (id, nome) values (42, 'Corki');
insert into campeao (id, nome) values (420, 'Illaoi');
insert into campeao (id, nome) values (421, 'Rek''Sai');
insert into campeao (id, nome) values (427, 'Ivern');
insert into campeao (id, nome) values (429, 'Kalista');
insert into campeao (id, nome) values (43, 'Karma');
insert into campeao (id, nome) values (432, 'Bard');
insert into campeao (id, nome) values (44, 'Taric');
insert into campeao (id, nome) values (45, 'Veigar');
insert into campeao (id, nome) values (48, 'Trundle');
insert into campeao (id, nome) values (497, 'Rakan');
insert into campeao (id, nome) values (498, 'Xayah');
insert into campeao (id, nome) values (5, 'Xin Zhao');
insert into campeao (id, nome) values (50, 'Swain');
insert into campeao (id, nome) values (51, 'Caitlyn');
insert into campeao (id, nome) values (516, 'Ornn');
insert into campeao (id, nome) values (517, 'Sylas');
insert into campeao (id, nome) values (518, 'Neeko');
insert into campeao (id, nome) values (523, 'Aphelios');
insert into campeao (id, nome) values (526, 'Rell');
insert into campeao (id, nome) values (53, 'Blitzcrank');
insert into campeao (id, nome) values (54, 'Malphite');
insert into campeao (id, nome) values (55, 'Katarina');
insert into campeao (id, nome) values (555, 'Pyke');
insert into campeao (id, nome) values (56, 'Nocturne');
insert into campeao (id, nome) values (57, 'Maokai');
insert into campeao (id, nome) values (58, 'Renekton');
insert into campeao (id, nome) values (59, 'Jarvan IV');
insert into campeao (id, nome) values (6, 'Urgot');
insert into campeao (id, nome) values (60, 'Elise');
insert into campeao (id, nome) values (61, 'Orianna');
insert into campeao (id, nome) values (62, 'Wukong');
insert into campeao (id, nome) values (63, 'Brand');
insert into campeao (id, nome) values (64, 'Lee Sin');
insert into campeao (id, nome) values (67, 'Vayne');
insert into campeao (id, nome) values (68, 'Rumble');
insert into campeao (id, nome) values (69, 'Cassiopeia');
insert into campeao (id, nome) values (7, 'LeBlanc');
insert into campeao (id, nome) values (711, 'Vex');
insert into campeao (id, nome) values (72, 'Skarner');
insert into campeao (id, nome) values (74, 'Heimerdinger');
insert into campeao (id, nome) values (75, 'Nasus');
insert into campeao (id, nome) values (76, 'Nidalee');
insert into campeao (id, nome) values (77, 'Udyr');
insert into campeao (id, nome) values (777, 'Yone');
insert into campeao (id, nome) values (78, 'Poppy');
insert into campeao (id, nome) values (79, 'Gragas');
insert into campeao (id, nome) values (8, 'Vladimir');
insert into campeao (id, nome) values (80, 'Pantheon');
insert into campeao (id, nome) values (81, 'Ezreal');
insert into campeao (id, nome) values (82, 'Mordekaiser');
insert into campeao (id, nome) values (83, 'Yorick');
insert into campeao (id, nome) values (84, 'Akali');
insert into campeao (id, nome) values (85, 'Kennen');
insert into campeao (id, nome) values (86, 'Garen');
insert into campeao (id, nome) values (875, 'Sett');
insert into campeao (id, nome) values (876, 'Lillia');
insert into campeao (id, nome) values (887, 'Gwen');
insert into campeao (id, nome) values (888, 'Renata Glasc');
insert into campeao (id, nome) values (89, 'Leona');
insert into campeao (id, nome) values (893, 'Aurora');
insert into campeao (id, nome) values (895, 'Nilah');
insert into campeao (id, nome) values (897, 'K''Sante');
insert into campeao (id, nome) values (9, 'Fiddlesticks');
insert into campeao (id, nome) values (90, 'Malzahar');
insert into campeao (id, nome) values (901, 'Smolder');
insert into campeao (id, nome) values (902, 'Milio');
insert into campeao (id, nome) values (91, 'Talon');
insert into campeao (id, nome) values (910, 'Hwei');
insert into campeao (id, nome) values (92, 'Riven');
insert into campeao (id, nome) values (950, 'Naafiri');
insert into campeao (id, nome) values (96, 'Kog''Maw');
insert into campeao (id, nome) values (98, 'Shen');